-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.socios
(
    dni serial NOT NULL,
    direccion character varying(70) NOT NULL,
    nombre character varying(30) NOT NULL,
    PRIMARY KEY (dni)
);

CREATE TABLE IF NOT EXISTS public.temas
(
    id_tema serial NOT NULL,
    tema character varying(30) NOT NULL,
    PRIMARY KEY (id_tema)
);

CREATE TABLE IF NOT EXISTS public.libros
(
    isbn serial NOT NULL,
    autor character varying(40) NOT NULL,
    n_ejemplares integer NOT NULL,
    id_tema integer NOT NULL,
    PRIMARY KEY (isbn)
);

CREATE TABLE IF NOT EXISTS public.prestados
(
    dni integer NOT NULL,
    isbn integer NOT NULL,
    fecha_prestamo date NOT NULL,
    fecha_devolucion date NOT NULL,
    id_prestamos serial NOT NULL
);

ALTER TABLE IF EXISTS public.libros
    ADD CONSTRAINT fk_libros_temas FOREIGN KEY (id_tema)
    REFERENCES public.temas (id_tema) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prestados
    ADD CONSTRAINT fk_prestados_libros FOREIGN KEY (isbn)
    REFERENCES public.libros (isbn) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prestados
    ADD CONSTRAINT fk_prestados_socios FOREIGN KEY (dni)
    REFERENCES public.socios (dni) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;