-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.libros
(
    isbn integer NOT NULL DEFAULT nextval('libros_isbn_seq'::regclass),
    autor character varying(40) COLLATE pg_catalog."default" NOT NULL,
    n_ejemplares integer NOT NULL,
    id_tema integer NOT NULL,
    CONSTRAINT libros_pkey PRIMARY KEY (isbn)
);

CREATE TABLE IF NOT EXISTS public.prestados
(
    dni integer NOT NULL,
    isbn integer NOT NULL,
    fecha_prestamo date NOT NULL,
    fecha_devolucion date NOT NULL,
    id_prestamos integer NOT NULL DEFAULT nextval('prestados_id_prestamos_seq'::regclass)
);

CREATE TABLE IF NOT EXISTS public.socios
(
    dni integer NOT NULL DEFAULT nextval('socios_dni_seq'::regclass),
    direccion character varying(70) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT socios_pkey PRIMARY KEY (dni)
);

CREATE TABLE IF NOT EXISTS public.temas
(
    id_tema integer NOT NULL DEFAULT nextval('temas_id_tema_seq'::regclass),
    tema character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT temas_pkey PRIMARY KEY (id_tema)
);

ALTER TABLE IF EXISTS public.libros
    ADD CONSTRAINT fk_libros_temas FOREIGN KEY (id_tema)
    REFERENCES public.temas (id_tema) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prestados
    ADD CONSTRAINT fk_prestados_libros FOREIGN KEY (isbn)
    REFERENCES public.libros (isbn) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prestados
    ADD CONSTRAINT fk_prestados_socios FOREIGN KEY (dni)
    REFERENCES public.socios (dni) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;